# Generated by Django 3.1.4 on 2021-12-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_carinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carinfo',
            name='info',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='carinfo',
            name='year',
            field=models.CharField(default='', max_length=10),
        ),
    ]
