# Generated by Django 3.1.4 on 2022-01-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='car_pics'),
        ),
    ]
